#!/usr/bin/python
import sys
import os
import argparse
import subprocess

libDir = os.path.dirname(os.path.realpath(__file__));
SUB_PARSER_NAME = 'subparser_name';

def callCmd(name, args):
	cmdPath = libDir+"/"+name+"/"+name+".py";
	print args;
	sys.exit();
	#subprocess.call(["python", cmdPath, args]);
	
def callReverse(args):
	callCmd(name='reverse', args=args);

parser = argparse.ArgumentParser(prog='React Tool Belt', description='Tool Belt for React Native');
subparser = parser.add_subparsers(title='Sub Commands', metavar='list', dest=SUB_PARSER_NAME);

# create the parser for the "reverse" command
parser_rev = subparser.add_parser('reverse', prog='Reverse', help='Call adb reverse PROTOCOL:PORT PROTOCOL:PORT');
parser_rev.add_argument('--port','-p', action='store', default='8081', help='port to reverse');
parser_rev.add_argument('--protocol', action='store', default='tcp', help='port to reverse');

args = parser.parse_args();
callCmd(name=args.subparser_name, args=args);
